### PR TITLE
update geometry_plane.py

### PR DESCRIPTION
**Pull request by FirefoxMetzger**
Closes: #372 

This PR updates the example by adding a light source and calling the rendering loop in the same way as it is done in the guide. This avoids seeing a frozen window only when running the example as a stand-alone.

Note that the unit test for this example worked fine. Likely, because it doesn't run the `__main__` block which needed updating.

I also took the liberty to update the imageIO code in there to v3 :D

### CODE REVIEW

**Review by almarklein — APPROVED** [review]
Although we tend to use `request_draw()` in our examples and docs, just setting `.draw_frame` should be a valid way to set the animate function. This should work because backends schedule a draw event when initializing (and when resizing).

I found the problem, and will create a PR to fix it. Nevertheless, I think these changes are still good, because the make it more consistent with the other examples, and it cleans up how imageio is used.

**Review by Korijn — DISMISSED** [review]
Agree with Almar's response!

**Comment by FirefoxMetzger** [comment]
> Although we tend to use request_draw() in our examples and docs, just setting .draw_frame should be a valid way to set the animate function. This should work because backends schedule a draw event when initializing (and when resizing).

Do you think it would be useful to converge on one canonical way to do this?

**Review by Korijn — APPROVED** [review]

**Comment by almarklein** [comment]
> Do you think it would be useful to converge on one canonical way to do this?

Well, it's the API of wgpu, which allows different ways of working in a few places (handling events being another). It gives some flexibility to apps built with it. I think I prefer leaving that as it is.

That said, in pygfx I'd focus on just one way to do things. I just checked, and this was the only use of `draw_frame` in pygfx :)

**Comment by almarklein** [comment]
To elaborate a bit. The `draw_frame` attribute allows one to subclass a canvas and implement `draw_frame` as a method.

**Pull request merged**
