### PR TITLE
clear a scene by removing all children

### PR DESCRIPTION
**Pull request by kushalkolar**
It's convenient to have a method that clears a scene, not sure if it's best to have this in `Scene` or the `WorldObject` base class?

### CODE REVIEW

**Comment by Korijn** [comment]
It would be preferable to have this on WorldObject:) thanks for the contribution!

**Comment by Korijn** [comment]
Is it possible for us maintainers to push commits to your branch? Would like to get this merged :)

**Comment by kushalkolar** [comment]
@Korijn sorry been a bit busy lately, I think you already be able to edit my branch? I'll get back to pygfx stuff in 2 weeks!

**Comment by Korijn** [comment]
Apparently I can! Took me a while to figure out how to do it. :) Here you go.

**Review by Korijn — APPROVED** [review]

**Pull request merged**
