### PR TITLE
Investigate RTD CI failure

### PR DESCRIPTION
**Pull request by almarklein**

### CODE REVIEW

**Comment by Korijn** [comment]
I wonder if it can be caused by lavapipe?

**Comment by almarklein** [comment]
> I wonder if it can be caused by lavapipe?

That's what I thought too.

It seems to consistently break at the same example. Its either `scene_in_a_scene.py` or the one that comes after.

**Comment by Korijn** [comment]
I compared the logs between the last passed build on RTD and the one that failed for the commit on this branch, specifically for the step `apt-get install --assume-yes --quiet -- libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers`:

Before:
```
Setting up libegl1-mesa:amd64 (22.0.1-1ubuntu2) ...
Setting up libllvm13:amd64 (1:13.0.1-2ubuntu2.1) ...
Setting up libvulkan1:amd64 (1.3.204.1-2) ...
Setting up libxcb-shape0-dev:amd64 (1.14-3ubuntu3) ...
Setting up libxcb-xfixes0-dev:amd64 (1.14-3ubuntu3) ...
Setting up mesa-vulkan-drivers:amd64 (22.0.1-1ubuntu2) ...
```

After:
```
Setting up libegl1-mesa:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libvulkan1:amd64 (1.3.204.1-2) ...
Setting up libxcb-shape0-dev:amd64 (1.14-3ubuntu3) ...
Setting up libxcb-xfixes0-dev:amd64 (1.14-3ubuntu3) ...
Setting up mesa-vulkan-drivers:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
```

**Comment by almarklein** [comment]
Well spotted! And so weird 🤔 

> Unless you know how to fix this, I suggest we open a ticket on https://github.com/readthedocs/readthedocs.org ?

Let's do that!

**Comment by Korijn** [comment]
The issue seems to have fixed itself upstream at the Ubuntu PPAs.

**Pull request closed without merging**
