### PR TITLE
fix `Controller.cameras` property, add a very basic test

### LINKED ISSUE #790: `Controllers.cameras` property not fully unpacking tuple
PR incoming, #778 introduced a bug.

I'll also add a basic test for controllers.

To reproduce:

```python
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx

canvas = WgpuCanvas()
renderer = gfx.renderers.WgpuRenderer(canvas)
scene = gfx.Scene()

geometry = gfx.klein_bottle_geometry(10, stitch=False)
geometry.texcoords = None
material = gfx.MeshPhongMaterial(color=(1, 0.5, 0, 1), flat_shading=True)
obj = gfx.Mesh(geometry, material)
scene.add(obj)

camera = gfx.PerspectiveCamera(70, 1)
camera.show_object(obj)

scene.add(gfx.AmbientLight(), camera.add(gfx.DirectionalLight()))


def draw():
    renderer.render(scene, camera)
    canvas.request_draw()


controller = gfx.OrbitController(camera, register_events=renderer)
print(controller.cameras)


if __name__ == "__main__":
    canvas.request_draw(draw)
    run()
```

Results in:

```python
Traceback (most recent call last):
  File "/home/kushal/repos/pygfx/examples/feature_demo/geometry_klein_bottle.py", line 39, in <module>
    print(controller.cameras)
          ^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/controllers/_base.py", line 93, in cameras
    return tuple(cam for cam, _ in self._cameras)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/controllers/_base.py", line 93, in <genexpr>
    return tuple(cam for cam, _ in self._cameras)
                         ^^^^^^
ValueError: too many values to unpack (expected 2)
```

### PR DESCRIPTION
**Pull request by kushalkolar**
fixes #790

### CODE REVIEW

**Comment by kushalkolar** [comment]
I'm guessing failure is related to the release of numpy v2 a few hours ago: https://github.com/pygfx/pygfx/actions/runs/9538926238/job/26288692137?pr=791#step:7:188

```python
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/runpy.py:288: in run_path
    return _run_module_code(code, init_globals, run_name,
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/runpy.py:97: in _run_module_code
    _run_code(code, mod_globals, init_globals,
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/runpy.py:87: in _run_code
    exec(code, run_globals)
examples/feature_demo/multi_slice2.py:21: in <module>
    from skimage.measure import marching_cubes
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/skimage/__init__.py:122: in <module>
    from ._shared import geometry
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

skimage is probably compiled against older numpy than v2

**Review by almarklein — APPROVED** [review]
Thanks for fixing this oversight!

**Comment by almarklein** [comment]
Thinking of the best way to fix the numpy issue 🤔   maybe an extra optional dep-group, so in our CI we can write `pip install -U -e .[examples,docs,numpyv1]`

**Review by Korijn — APPROVED** [review]
Ty for the test too!

**Comment by almarklein** [comment]
Fixing CI in #793

**Pull request merged**
