### PR TITLE
add image overlay example

### LINKED ISSUE #550: Set alpha values for different parts of an `Image`
Is is possible to set the alpha values separately for each point of an `Image`? This would be useful for layering images on top with different blending modes.

### PR DESCRIPTION
**Pull request by kushalkolar**
closes #550 

Simple image overlay example

image

### CODE REVIEW

**Comment by kushalkolar** [comment]
I can't really figure out the docs failure: https://github.com/pygfx/pygfx/actions/runs/5341833747/jobs/9683040774?pr=554#step:6:1113

```python
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done

Sphinx-Gallery successfully executed 102 out of 103 files subselected by:


Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/home/runner/work/pygfx/pygfx/examples/feature_demo/image_overlay.py failed leaving traceback:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/sphinx_gallery/scrapers.py", line 340, in save_figures
    rst = scraper(block, block_vars, gallery_conf)
  File "/home/runner/work/pygfx/pygfx/pygfx/utils/gallery_scraper.py", line 81, in pygfx_scraper
    iio.imwrite(img_path, canvas.draw())
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/imageio/v3.py", line 147, in imwrite
    encoded = img_file.write(image, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/imageio/plugins/pillow.py", line 415, in write
    for frame in ndimage:
TypeError: iteration over a 0-d array


-------------------------------------------------------------------------------
    gallery_conf["filename_pattern"] = '^((?![\\\\/]other[\\\\/]).)*$'
    gallery_conf["ignore_pattern"]   = '__init__\\.py'

after excluding 0 files that had previously been run (based on MD5).

make: *** [Makefile:25: html] Error 2
Error: Process completed with exit code 2.
```

**Comment by Korijn** [comment]
Are you using a different version of imageio maybe? Seems like the coffee image is empty on CI?

**Comment by Korijn** [comment]
I think you have to move this line out of the if statement: `canvas.request_draw(lambda: renderer.render(scene, camera))`

**Comment by kushalkolar** [comment]
This is good to go!

Seems like the position of `# sphinx_gallery_pygfx_render` matters

**Review by almarklein — APPROVED** [review]

**Review by Korijn — APPROVED** [review]

**Pull request merged**
