### PR TITLE
Modify image shader to set image position

### PR DESCRIPTION
**Pull request by kushalkolar**
followup from #367 

without `positions` specified:

```python
image = gfx.Image(
    gfx.Geometry(grid=gfx.Texture(im, dim=2)),
    gfx.ImageBasicMaterial(clim=(0, 255)),
)
```
image

with `positions`, uses the positions to apply an offset:

```python
positions = [
    [100, 100, 0],
]

image = gfx.Image(
    gfx.Geometry(grid=gfx.Texture(im, dim=2), positions=positions),
    gfx.ImageBasicMaterial(clim=(0, 255)),
)
```

image

### CODE REVIEW

**Comment by kushalkolar** [comment]
We could also allow `positions` to be a `4 x 3` array if a user want to manually assign the positions of all 4 corners, currently it requires a `1 x 3` array to just set the top left offset.

**Comment by kushalkolar** [comment]
So after [this](https://github.com/pygfx/pygfx/issues/367#issuecomment-1301446101), could it still be useful to allow a `4 x 3` array in some use cases to display the image in a warped way, like as a trapezoid for example instead of a rectangle?

**Comment by almarklein** [comment]
My inclination is that for such use-cases a mesh should be used. I can imagine support for deforming an image or volume, but then I think it would be another texture with per-pixel deformation.

**Comment by Korijn** [comment]
Converting this to a draft to signal that it is not clear if we want to merge this or not.

**Comment by kushalkolar** [comment]
> My inclination is that for such use-cases a mesh should be used. I can imagine support for deforming an image or volume, but then I think it would be another texture with per-pixel deformation.

makes sense. Perhaps we could raise exceptions if certain `Geometry` arguments aren't supported for specific WorldObjects? Setting `positions` for Image geometry doesn't raise any exception, it has no effect which is confusing for users.

**Comment by almarklein** [comment]
> Perhaps we could raise exceptions if certain Geometry arguments aren't supported for specific WorldObjects? 

The problem with that is that we don't know how a geometry is used. It might be used by different world objects. E.g. the geometry for a mesh might also be used by a `Points`  object. In the example of `Image`, someone could in theory create a custom shader that does handle both `grid`  and `positions`.

**Comment by Korijn** [comment]
My proposal:

* Close this PR
* Open a new issue if you want to further discuss the Geometry API
* Personally I would focus on providing high quality documentation and guides, rather than making the renderer perform validation on WorldObject/Geometry combinations. Performance is critical so we don't want to spend time every frame validating scene graphs.

**Pull request closed without merging**
