### PR TITLE
Per-point sizes and colors

### PR DESCRIPTION
**Pull request by brisvag**
Trying my hand at a first contribution. I'm a bit confused by how buffers are bound and accessed.

Right now, this doesn't work (sizes are not read at all, it seems).

### CODE REVIEW

**Comment by almarklein** [comment]
BTW we use `black .` for autoformatting and `flake8 .` for style checks.

**Comment by brisvag** [comment]
> What about instead of a separate property, we define a special value, e.g. `PointMaterial(color="pervertex")`

I like this more: no conflicting arguments. One step further: does this have to be hardcoded to use a specific name in the geometry?

```python
geometry = gfx.Geometry(positions=positions, arbitrary_name=some_data)
material = gfx.PointsMaterial(color='arbitrary_name')
```

**Comment by Korijn** [comment]
I think it is good to expect a fixed name (e.g. `colors` and `sizes`). It makes code consistent and is just less configuration for users to worry about.

I'm not sure but is the color attribute standardized even in gltf etc?

**Comment by Korijn** [comment]
That's right.

**Comment by Korijn** [comment]
> > material should either:
> > 
> > * have boolean flags like `point_sizes` to enable using the geomtry-provided values, or
> > * allow a special value for `size` such as `pervertex`
> 
> I'm not sure which I like better. I dislike having tons of flags in the future for every property that can also be set per-vertex. But the fact that a color property can be something different than a color is also not great.
> 
> If we go with the boolean flag, let's use something that looks more like a boolean. E.g. `use_vertex_color`?
> 
> Ha, @Korijn do you remember that in Arbiter 1.0 we had props that could be set to e.g. ":x" to select column `x`? Memories :) Also, here's a link to Bokeh docs showing a similar pattern to use string names to select columns from a datasource: https://docs.bokeh.org/en/latest/docs/user_guide/data.html

Let's do the flag!

**Comment by Korijn** [comment]
Can we tackle that when we get to face colors?

**Comment by brisvag** [comment]
Yes! This is the updated example:

image

**Pull request merged**
