### PR TITLE
MeshMaterial properties

### PR DESCRIPTION
**Pull request by almarklein**
* [x] Added `MeshPhongMaterial.shininess`.
* [x] Added `MeshPhongMaterial.emissive`.

### CODE REVIEW

**Comment by Korijn** [comment]
https://threejs.org/examples/?q=phong#webgl_materials_variations_phong

Have you seen this example? Maybe it's useful as an example.

**Comment by almarklein** [comment]
Any other props that we need? A lot of what I see seem somewhat "advanced" e.g. related to environment maps. Maybe emissive color?

**Comment by Korijn** [comment]
Emissive and specular color both seem like they don't depend on any additional maps. Can't think of anything else.

**Comment by almarklein** [comment]
Done.

**Comment by Korijn** [comment]
LGTM!

**Pull request merged**
