### PR TITLE
Add texture's data to be set

### PR DESCRIPTION
**Pull request by hmaarrfk**
This helps avoid a copy when users overwrite the data.

I'm not sure if this is allowed, but it seems to "work".

### CODE REVIEW

**Comment by hmaarrfk** [comment]
i can add checks for continuity and same shape if you want.

**Comment by almarklein** [comment]
I'm a bit hesitant, because currently the array that's passed to the texture stays the data placeholder. We even mention that in the docs "Note: the data is the same reference that was given to instantiate this object". It also says "but this may change", but I don't know what code in pygfx and downstream libs assume that the array does not change.

This relates to #19, which lists some possibilities for buffers, but some also apply to textures. Also relates to #600. If we are to change it, it'd probably be best to do it together with other (possibly breaking) changes to buffer/texture.

I assume the main point is speed by avoiding data copies?

**Comment by hmaarrfk** [comment]
> I assume the main point is speed by avoiding data copies?
Yes the main point is to avoid data copies.

To be precise, when working with "4k" sized images this has a very noticeable effect on performance for me.

Thank you for pointing me to both those issues. I've subscribed and will try to contribute to those discussions however I can.

From my leanings this past week:

1. Changing the size of the data should not be allowed, at least not without other logic. 
    * NB. This was possible with vispy / opengl (though it is unclear if this was a bug we took advantage of).
2. I haven't really tested with anything other than just Intel integrated graphics + linux. So I too fear that there may some things that aren't OK with other processing pipelines.

Memory copies are really important to consider. So hopefully I can learn more about GSL and WGPU to be able to better contribute.

Thank you for the discussion. I'll close this and discuss on the aforementioned issues.

**Comment by almarklein** [comment]
AFAIK the size of a texture in OpenGL is fixed, but I think we handled size changes in vispy at a relatively low level. In pygfx we opted (for now) to more "closely" wrap the GPU texture.

Do you think there are use-cases where being able to change the size has advantages? Under the hood a new texture object will have to be created anyway, so in terms of performance it won't differ from creating a new `gfx.Texture`.

**Comment by hmaarrfk** [comment]
> Do you think there are use-cases where being able to change the size has advantages?

I don't really think so.

Personally, my biggest challenge right now is dealing with the "-0.5" offset in the images that seems to be occuring from somewhere in the pipeline ;) it will take me some time, but i'll figure it out. Your examples have been tremendously helpful.

I think that overtime, we got better at managing things between vispy and now pygfx so the advantages that seemed good 5 years ago when we first built our display pipeline are not actually useful.

For "changing the texture size" (that is the number of bytes) isn't so useful since removing and adding textures seems very very fast in pygfx.

**Comment by almarklein** [comment]
> Personally, my biggest challenge right now is dealing with the "-0.5" offset in the images

The `gfx.Image` indeed has an offset so that the pixel center's are aligned with the grid, i.e. the bottomleft pixel is on top of the origin. This is hard-coded in the shader:
https://github.com/pygfx/pygfx/blob/329586c59e1dd98519794b0ef6159552ccd19ef6/pygfx/renderers/wgpu/imageshader.py#L63-L76

But you should be able to undo it by doing `image.local.position = 0.5, 0.5, 0`.

> [...] removing and adding textures seems very very fast in pygfx.

Yes it should be pretty fast. The bindings will be updated, and therefore the pipeline object recomposed, but there is no shader recompilation, which would be much more expensive.

**Comment by hmaarrfk** [comment]
I should say that 
```
             let pos1 = vec2<f32>(-0.5); 
```

is probably the right way to interpret images. it is just a little annoying to do this change at the visualization level in our codebase.

**Comment by hmaarrfk** [comment]
I've been listening and reading alot about WGPU and why it was created over vulkan.

Their primary desire was to ensure safety for the web, and rust really prides itself on  being memory safe.

I would be surprised if, given the little code I wrote that the proposed operation was not safe. It mostly avoids a python side copy in the data transfer chain.

**Comment by almarklein** [comment]
I agree. My main reason from being hesitant is related to expectations about how the pygfx Texture object relates to the data it holds. I also agree we should probably support a path to avoid data copies when updating all data. I added a note to the top post of #19.

**Comment by hmaarrfk** [comment]
A small question. Is the whole `_rev` stuff supposed to be a unique global counter? or just "each object's rev should be different when updating a particular object"

**Comment by almarklein** [comment]
The id of a worldObject is globally unique. The `_rev`'s are per-object and should be monotonously increasing at each update.

**Pull request closed without merging**
