### PR TITLE
Update to new wgpu

### PR DESCRIPTION
**Pull request by almarklein**
* [x] Update the way we update buffers and texturs (new wgpu API).
* [x] Refactor Buffer and Texture classes to use memoryviews, no more BaseBuffer and a numpy-specific Buffer.
* [x] Update depth texture size by comparing with the render texture view.
* [x] Set camera viewport in the renderer, so it does not have to be done in each example.
* [x] Use full-res images in the examples (no more silly 1MB limit)
* [x] Clean up examples.
* [x]  Make skybox and volume_slice2 example work. (DONE, not committed yet, needs cleaning up)

### CODE REVIEW

**Comment by Korijn** [comment]
In the case of rendering directly to an image (without a GUI), we still need to be able to set the size of the resulting image and thus the camera viewport, somehow. I understand that it is something we don't support yet, but we should at least consider the implications for the API.

**Comment by almarklein** [comment]
Right now, the renderer has a reference to the canvas. When we implement offscreen rendering, the renderer can just get a size, or some sort of OffscreenCanvas thingy, whatever. Regardless, I think that one way or another, the renderer will  be aware of the size.

**Comment by Korijn** [comment]
Ok!

**Comment by almarklein** [comment]
The examples now use standard images from imageio. Make sure to update imageio first :)

**Pull request merged**
