### PR TITLE
Make hte resources path more resilient to changing python environment

### PR DESCRIPTION
**Pull request by hmaarrfk**
Ok this is quite an edge case but consider this:

1. An early adopter developer trying to test your code.
2. They install some supported version.
3. They need to test some example on the main branch. (such as your cool new ruler)
4. They run `pip install -e . -vv` to using the main branch in editable mode
5. The font caching engine then tries to re-open a a Noto-font file but can't resolve the resource correctly.

I feel like using `__file__` is likely easy enough but maybe it isn't comptaible with some pyinstaller stuff?

Trying to test on the CIs.

### CODE REVIEW

**Comment by almarklein** [comment]
I think the use-case you outline should work. I also use `pip install -e .`. In what way does it fail?

**Comment by hmaarrfk** [comment]
Because I already have an other window of my application open at the same time ;) do the existing application breaks. 

As I said. Very bad bad behavior from my part ;)

**Comment by hmaarrfk** [comment]
Let me try to take a screen cast at some point today

**Comment by hmaarrfk** [comment]
I'm not really sure what was breaking in my shader code before. I can't recreate right at this moment.

I'll have to circle back to this once i have a recreator and a fix.

**Pull request closed without merging**
