### PR TITLE
Adjust to new wgpu-py

### PR DESCRIPTION
**Pull request by almarklein**

### CODE REVIEW

**Review by Korijn — APPROVED** [review]

**Comment by almarklein** [comment]
If we merge this, pygfx `main` requires the unreleased `wgpu`. Can also leave this PR open until we've made a release of new wgpu-py.

**Comment by Korijn** [comment]
Let's hold off then until resolved in wgpu-py

**Review by Korijn — CHANGES_REQUESTED** [review]
Waiting for upstream fix in wgpu-py

**Comment by hmaarrfk** [comment]
i feel like a new version was just released right? 

Typically I try to not use try/except statements. is there a version that code like this can depend on?

**Comment by almarklein** [comment]
🥳

**Review by Korijn — APPROVED** [review]

**Pull request merged**
