### PR TITLE
Fix shadow camera cull mode

### LINKED ISSUE #453: Sponza Rendering needs a second look
xref: https://github.com/pygfx/pygfx/pull/442#issuecomment-1404951278

Even after adjusting the near plane when rendering the sponza scene, there still seems to be a glitch/bug in the lighting that needs solving:

image

I don't know what the cause is, but could it be that the model of the lamp holder is not closed at the bottom and as such light can slip through?

### LINKED ISSUE #476: Shadow glitch
Hello everyone, been playing with your examples. Remarkable code; god level commenting; thank you.
Looking at your 'Types of Cylinders' example [https://pygfx.readthedocs.io/en/latest/_gallery/feature_demo/cylinder.html#sphx-glr-gallery-feature-demo-cylinder-py](url), I'm convinced the shadows cast are incorrect. The full cylinder seems okay, but the other two objects appear to be missing shadows that ought to be cast by the faces closest the light source.
Don't know code well enough to contribute there I'm afraid; just trying to help :)

### PR DESCRIPTION
**Pull request by Korijn**
* Closes #476
* Closes #453 

Before:
image
image
image

After:
image
image
image

### CODE REVIEW

**Comment by Korijn** [comment]
Converting to draft as @panxinmiao shared some new insights in #476

**Comment by Korijn** [comment]
As per #467 my next move is to see if the cylinders example can be fixed purely through configuration.

**Comment by Korijn** [comment]
@almarklein how would I go about making the cull mode a settable property that is properly hooked into the reactivity mechanics?

**Comment by almarklein** [comment]
If you store the internal variable on `self._store` it is tracked. However, the tracking only happens for stuff drawn by the renderer's pipeline building logic. It looks like the shadow stuff builds its own pipeline as a sort of pre-processing step.

**Comment by Korijn** [comment]
I've made `light.shadow.cull_mode` configurable and managed to resolve all the rendering artifacts just by setting `cull_mode` and `bias` to appropriate values for each example.

**Comment by almarklein** [comment]
> `# TODO: move bias and cull_mode to Light so they can be reactive?`

That would not help. We could add the `Trackable` mechanics on this class, but in this particular case I think it would be easier to just set a flag in the setters and check that somewhere to see whether the shadow pipeline needs to be rebuild.

**Review by almarklein — APPROVED** [review]
Only comment is maybe include that link (https://learnopengl.com/Advanced-Lighting/Shadows/Shadow-Mapping) somewhere. Though we could also find it back on the issue or this PR.

**Comment by Korijn** [comment]
> > `# TODO: move bias and cull_mode to Light so they can be reactive?`
> 
> That would not help. We could add the `Trackable` mechanics on this class, but in this particular case I think it would be easier to just set a flag in the setters and check that somewhere to see whether the shadow pipeline needs to be rebuild.

I've created #489 to track this.

> Only comment is maybe include that link (https://learnopengl.com/Advanced-Lighting/Shadows/Shadow-Mapping) somewhere. Though we could also find it back on the issue or this PR.

Well... I think we would do better to write a short guide that explains how to configure shadow mapping. But not for now.

**Pull request merged**
