### PR TITLE
Implement colorspace tex-srgb

### PR DESCRIPTION
**Pull request by almarklein**
Ref #557

This, I think, solves the remaining point in #557. In my view, there are valid cases for handling srgb both by conversion in the shader, as by using an `-srgb` texture format. This implements the latter.

### CODE REVIEW

**Comment by almarklein** [comment]
Interesting to see that the glTF-compliant method produces less pretty results (see the bands in the new validation screenshot).

**Comment by Korijn** [comment]
@panxinmiao

**Review by Korijn — APPROVED** [review]

**Comment by panxinmiao** [comment]
> Interesting to see that the glTF-compliant method produces less pretty results (see the bands in the new validation screenshot).

In fact, in this use case, the "banding" effect in the image is actually correct. This is because the color data is in the sRGB space, while np.linspace(0, 255, 6) performs interpolation in linear space. The gradient between the generated colors is not linear because the sRGB space itself is non-linear. In sRGB space, the gradient between colors is uneven.

This use case precisely demonstrates the error of interpolating directly in the sRGB space. To generate smooth gradient colors in sRGB space, the data should first be converted to linear space, then interpolated, and finally converted back to sRGB space.



```python

import numpy as np

# Generate interpolation in linear space
lin_rgb = np.linspace(0, 1, 6)  # Linear interpolation from 0 to 1
# Convert linear RGB back to sRGB space
srgb = np.clip(lin_rgb ** (1/2.2), 0, 1) 

# Scale the interpolation result back to the range of 0-255
srgb_255 = np.clip(srgb * 255, 0, 255).astype(np.uint8)
```

**Comment by panxinmiao** [comment]
If the image data is in the "smooth" sRGB space (i.e., the data is non-linear), and interpolation is performed before sampling as it is currently done, I expect that it would actually result in "banding."

**Comment by almarklein** [comment]
@panxinmiao I don't entirely agree 😄   But I think we do agree that both approaches have valid use-cases, and this PR tries to make it so that we have can both. Do you have any comments on the implementation or is this good to go from your end?

----

In the mean time we can discuss this band effect.

I meant to create a gradient in sRGB space, so `np.linspace()`  interpolates in the sRGB space, simply because I state that the data is sRGB. I started with 100 samples, in which case the band looks smooth in all cases. Then I used less samples and see how the results differ. Although downsampled, it's still sRGB space. It's the same effect of using a lower resolution texture map.

The shader is sampling from source data that is in sRGB space, so it makes perfect sense that the result looks better if the interpolation happens in the sRGB space.

If the image would represent "physical" data, then the "source" is in linear space, so missing values are best reconstructed by interpolation in the linear space.

**Comment by panxinmiao** [comment]
I understand your point. In this use case, you aim to create an image that appears visually smooth in the sRGB space, which requires performing linear interpolation directly in the sRGB space. However, the corresponding physical color values would then be nonlinear. Following the "tex-srgb" workflow (i.e., decoding first and then performing interpolation in the physical space), banding artifacts will occur, which is expected. However, this is a special use case (working directly in the sRGB space), whereas modern rendering engines and related shader and lighting algorithms are typically designed for linear workflows and operate in linear space.

To address your requirement, we only need to set both the input and output textures to non-sRGB formats (although we currently don’t support setting the output texture format). I understand that you may consider the data to "represent" sRGB space values, but this is not critical. For the program, data is just data, and its meaning is defined by the user. Texture formats simply dictate how data is processed and do not necessarily align with its actual significance. By configuring this way, we essentially instruct the program to "process the data directly without decoding into physical space." Since no space conversion is applied, you can think of the shader algorithms as effectively operating in the sRGB space.

**Comment by panxinmiao** [comment]
>  Do you have any comments on the implementation or is this good to go from your end?

I think the current approach is acceptable, at least it can solve some of the current needs. However, it is evident that this will increase the complexity of shaders and code.

**Comment by almarklein** [comment]
In #910 you mention that "this issue still needs further resolution". I was under the impression that the gltf loader can simply set `colorspace="tex-srgb"` for things to work as glTF intended. What part is still missing?

**Comment by panxinmiao** [comment]
> I was under the impression that the gltf loader can simply set `colorspace="tex-srgb"` for things to work as glTF intended. What part is still missing?

This is exactly what I mean.

Additionally, the logic related to texture colorspaces needs to be adjusted. My idea is to standardize the logic for all textures and ensure that each texture’s colorspace property is truly effective (rather than just the colormap’s colorspace being considered).

For example, for an env_map, typically in the sRGB space, when loading from glTF, we simply specify its colorspace as "tex-srgb" in the glTF loader. However, for environment map textures created by the user, they can choose "tex-srgb", "srgb", or even "physical" (any of these cases are possible). We need to handle these different settings. When the user specifies "srgb", the shader must be able to handle the space conversion (even though this may not be entirely correct or fully compliant with the glTF specification). When "tex-srgb" or "physical" is specified, no conversion should be performed.

The increase in shader code complexity that I mentioned earlier refers to this issue.

**Comment by almarklein** [comment]
I'm not sure what the problem is. The colorspace attribute is honored in (AFAICT) all cases where the texture is interpreted as color. 

And yes, this has made the code a bit more complex, but that's the price we pay (and one that I'm happy to pay) for supporting the different use-cases related to srgb.

**Comment by panxinmiao** [comment]
> I'm not sure what the problem is. 

What I meant in #910 is just to note down the tasks that are still pending:

1. Setting the correct format for each texture in the glTF loader.
2. Handling the colorspace of each texture in the shaders.

I plan to complete these tasks in a single PR. Simply noting that the issue with that test case has not been fully resolved before that PR :)

**Pull request merged**
